name: PR checks

on:
  pull_request:

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - run: nix flake check --all-systems
  run-checks-template:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - run: |
          cd templates/chez-bin
          nix flake update --override-input flakelight-chez ../..
          echo '(display "Hello, World!\n")' > main.ss
          git add .
          nix flake check --all-systems
